export default [
  { src: '/showcase-thumbnails/front/1.jpg', alt: 'Front - 1' },
  { src: '/showcase-thumbnails/front/2.jpg', alt: 'Front - 2' },
  { src: '/showcase-thumbnails/lobby/1.jpg', alt: 'Lobby - 1' },
  { src: '/showcase-thumbnails/lobby/2.jpg', alt: 'Lobby - 2' },
  { src: '/showcase-thumbnails/lobby/3.jpg', alt: 'Lobby - 3' },
  { src: '/showcase-thumbnails/lobby/4.jpg', alt: 'Lobby - 4' },
  { src: '/showcase-thumbnails/back/1.jpg', alt: 'Back - 1' },
  { src: '/showcase-thumbnails/back/2.jpg', alt: 'Back - 2' },
  { src: '/showcase-thumbnails/back/3.jpg', alt: 'Back - 3' },
  { src: '/showcase-thumbnails/common/1.jpg', alt: 'Common - 1' },
  { src: '/showcase-thumbnails/rooms/qd/1.jpg', alt: 'Rooms - QD - 1' },
  { src: '/showcase-thumbnails/rooms/qd/2.jpg', alt: 'Room - QD - 2' },
  { src: '/showcase-thumbnails/rooms/ql/1.jpg', alt: 'Room - QL - 1' },
  { src: '/showcase-thumbnails/rooms/ql/2.jpg', alt: 'Room - QL - 2' },
  { src: '/showcase-thumbnails/rooms/ql/3.jpg', alt: 'Room - QL - 3' },
  { src: '/showcase-thumbnails/rooms/fr/1.jpg', alt: 'Room - FR - 1' },
  { src: '/showcase-thumbnails/rooms/fr/2.jpg', alt: 'Room - FR - 2' },
  { src: '/showcase-thumbnails/rooms/fr/3.jpg', alt: 'Room - FR - 3' },
  { src: '/showcase-thumbnails/rooms/fr/4.jpg', alt: 'Room - FR - 4' }
]
